package com.seckill.componet.dao;

import com.seckill.componet.dataobject.MiaoshaGoods;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MiaoshaGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaGoods
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaGoods
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    int insert(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaGoods
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    int insertSelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaGoods
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    MiaoshaGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaGoods
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    int updateByPrimaryKeySelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaGoods
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    int updateByPrimaryKey(MiaoshaGoods record);

    //库存减1
    void reduceMiaoshaGoodsStock(@Param("id") Long id);

}