package com.seckill.componet.dao;

import com.seckill.componet.dataobject.MiaoshaOrder;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MiaoshaOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaOrder
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaOrder
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    int insert(MiaoshaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaOrder
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    int insertSelective(MiaoshaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaOrder
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    MiaoshaOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaOrder
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    int updateByPrimaryKeySelective(MiaoshaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaoshaOrder
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    int updateByPrimaryKey(MiaoshaOrder record);

    /**
     * 根据userId，goodsId查询秒杀订单
     * @param userId
     * @param goodsId
     * @return
     */
    MiaoshaOrder getMsOrderByUserIdGoodsId(@Param("userId") long userId,@Param("goodsId") long goodsId);

    MiaoshaOrder getMsOrderByUserIdOrderId(@Param("orderId") long orderId);
}