package com.seckill.componet.dataobject;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.id
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_name
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_title
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    private String goodsTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_img
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_detail
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    private String goodsDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_price
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    private Long goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goods_stock
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    private Integer goodsStock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.id
     *
     * @return the value of tb_goods.id
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.id
     *
     * @param id the value for tb_goods.id
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_name
     *
     * @return the value of tb_goods.goods_name
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_name
     *
     * @param goodsName the value for tb_goods.goods_name
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_title
     *
     * @return the value of tb_goods.goods_title
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public String getGoodsTitle() {
        return goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_title
     *
     * @param goodsTitle the value for tb_goods.goods_title
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle == null ? null : goodsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_img
     *
     * @return the value of tb_goods.goods_img
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_img
     *
     * @param goodsImg the value for tb_goods.goods_img
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_detail
     *
     * @return the value of tb_goods.goods_detail
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public String getGoodsDetail() {
        return goodsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_detail
     *
     * @param goodsDetail the value for tb_goods.goods_detail
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public void setGoodsDetail(String goodsDetail) {
        this.goodsDetail = goodsDetail == null ? null : goodsDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_price
     *
     * @return the value of tb_goods.goods_price
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public Long getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_price
     *
     * @param goodsPrice the value for tb_goods.goods_price
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public void setGoodsPrice(Long goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goods_stock
     *
     * @return the value of tb_goods.goods_stock
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public Integer getGoodsStock() {
        return goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goods_stock
     *
     * @param goodsStock the value for tb_goods.goods_stock
     *
     * @mbg.generated Thu Nov 21 16:53:38 CST 2019
     */
    public void setGoodsStock(Integer goodsStock) {
        this.goodsStock = goodsStock;
    }
}