package com.seckill.componet.dataobject;

public class MiaoshaOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaoshaOrder.id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaoshaOrder.user_id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaoshaOrder.order_id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaoshaOrder.goods_id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    private Long goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaoshaOrder.id
     *
     * @return the value of tb_miaoshaOrder.id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaoshaOrder.id
     *
     * @param id the value for tb_miaoshaOrder.id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaoshaOrder.user_id
     *
     * @return the value of tb_miaoshaOrder.user_id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaoshaOrder.user_id
     *
     * @param userId the value for tb_miaoshaOrder.user_id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaoshaOrder.order_id
     *
     * @return the value of tb_miaoshaOrder.order_id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaoshaOrder.order_id
     *
     * @param orderId the value for tb_miaoshaOrder.order_id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaoshaOrder.goods_id
     *
     * @return the value of tb_miaoshaOrder.goods_id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaoshaOrder.goods_id
     *
     * @param goodsId the value for tb_miaoshaOrder.goods_id
     *
     * @mbg.generated Thu Nov 21 16:52:49 CST 2019
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }
}