package com.seckill.componet.dataobject;

import java.util.Date;

public class MiaoshaGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaoshaGoods.id
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaoshaGoods.goods_id
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaoshaGoods.miaosha_price
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    private Long miaoshaPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaoshaGoods.stock_count
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    private Integer stockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaoshaGoods.start_date
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaoshaGoods.end_date
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaoshaGoods.id
     *
     * @return the value of tb_miaoshaGoods.id
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaoshaGoods.id
     *
     * @param id the value for tb_miaoshaGoods.id
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaoshaGoods.goods_id
     *
     * @return the value of tb_miaoshaGoods.goods_id
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaoshaGoods.goods_id
     *
     * @param goodsId the value for tb_miaoshaGoods.goods_id
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaoshaGoods.miaosha_price
     *
     * @return the value of tb_miaoshaGoods.miaosha_price
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public Long getMiaoshaPrice() {
        return miaoshaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaoshaGoods.miaosha_price
     *
     * @param miaoshaPrice the value for tb_miaoshaGoods.miaosha_price
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public void setMiaoshaPrice(Long miaoshaPrice) {
        this.miaoshaPrice = miaoshaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaoshaGoods.stock_count
     *
     * @return the value of tb_miaoshaGoods.stock_count
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaoshaGoods.stock_count
     *
     * @param stockCount the value for tb_miaoshaGoods.stock_count
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaoshaGoods.start_date
     *
     * @return the value of tb_miaoshaGoods.start_date
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaoshaGoods.start_date
     *
     * @param startDate the value for tb_miaoshaGoods.start_date
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaoshaGoods.end_date
     *
     * @return the value of tb_miaoshaGoods.end_date
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaoshaGoods.end_date
     *
     * @param endDate the value for tb_miaoshaGoods.end_date
     *
     * @mbg.generated Thu Nov 21 16:53:56 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}