package com.seckill.componet.dataobject;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.user_id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.goods_id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.address_id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    private Long addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.goods_name
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.goods_count
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    private Integer goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.goods_price
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    private Double goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_channel
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    private Integer orderChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.status
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.create_date
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.pay_date
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    private Date payDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.id
     *
     * @return the value of tb_order.id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.id
     *
     * @param id the value for tb_order.id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.user_id
     *
     * @return the value of tb_order.user_id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.user_id
     *
     * @param userId the value for tb_order.user_id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.goods_id
     *
     * @return the value of tb_order.goods_id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.goods_id
     *
     * @param goodsId the value for tb_order.goods_id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.address_id
     *
     * @return the value of tb_order.address_id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.address_id
     *
     * @param addressId the value for tb_order.address_id
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.goods_name
     *
     * @return the value of tb_order.goods_name
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.goods_name
     *
     * @param goodsName the value for tb_order.goods_name
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.goods_count
     *
     * @return the value of tb_order.goods_count
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.goods_count
     *
     * @param goodsCount the value for tb_order.goods_count
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.goods_price
     *
     * @return the value of tb_order.goods_price
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.goods_price
     *
     * @param goodsPrice the value for tb_order.goods_price
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_channel
     *
     * @return the value of tb_order.order_channel
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public Integer getOrderChannel() {
        return orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_channel
     *
     * @param orderChannel the value for tb_order.order_channel
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public void setOrderChannel(Integer orderChannel) {
        this.orderChannel = orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.status
     *
     * @return the value of tb_order.status
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.status
     *
     * @param status the value for tb_order.status
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.create_date
     *
     * @return the value of tb_order.create_date
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.create_date
     *
     * @param createDate the value for tb_order.create_date
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.pay_date
     *
     * @return the value of tb_order.pay_date
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.pay_date
     *
     * @param payDate the value for tb_order.pay_date
     *
     * @mbg.generated Thu Nov 21 16:52:16 CST 2019
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }
}