package com.seckill.componet.dataobject;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.tel
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.salt
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.head
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    private String head;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.register_date
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    private Date registerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.last_login_date
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    private Date lastLoginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.login_count
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    private Integer loginCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.tel
     *
     * @return the value of tb_user.tel
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.tel
     *
     * @param tel the value for tb_user.tel
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.salt
     *
     * @return the value of tb_user.salt
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.salt
     *
     * @param salt the value for tb_user.salt
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.head
     *
     * @return the value of tb_user.head
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.head
     *
     * @param head the value for tb_user.head
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public void setHead(String head) {
        this.head = head == null ? null : head.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.register_date
     *
     * @return the value of tb_user.register_date
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.register_date
     *
     * @param registerDate the value for tb_user.register_date
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.last_login_date
     *
     * @return the value of tb_user.last_login_date
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.last_login_date
     *
     * @param lastLoginDate the value for tb_user.last_login_date
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.login_count
     *
     * @return the value of tb_user.login_count
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.login_count
     *
     * @param loginCount the value for tb_user.login_count
     *
     * @mbg.generated Tue Nov 19 22:17:22 CST 2019
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }
}